config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations'}
  root to: 'phrases#index', as: :root

  resources :phrases do
    member do
      post :vote
    end
    resources :examples, only: [:create, :destroy] do
      post :vote
    end
  end

  resources :notifications, only: :index do
    collection do
      put :read_all
    end
  end

  resources :users, only: [:show, :index]
  get 'static_pages/hello'
end

app/views/layouts/_navigation.html.slim
header.navbar.navbar-inverse
  .container
    a.navbar-brand href="#"
      |EngliApp
    nav
      ul.nav.navbar-nav.pull-right
        li
        - if signed_in?
          li = link_to "Home", root_path
          li = link_to "Users", users_path
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              ' User
              - if current_user.has_new_notifications?
                span.willhidebyajax.glyphicon.glyphicon-flash.navigation-notification-item
              span.caret
            ul.dropdown-menu
              li = link_to "Logged as: " + current_user.username, user_path(current_user)
              li.divider
              li = link_to "View Profile", user_path(current_user)
              li = link_to "Edit Profile", edit_user_registration_path
              li = link_to notifications_path do
                ' Notifications
                - if current_user.has_new_notifications?
                  span.willhidebyajax.glyphicon.glyphicon-flash.navigation-notification-item
              li = link_to "Sign Out", destroy_user_session_path, method: "delete"
        - else
          li = link_to "Sign In", new_user_session_path
          li = link_to "Sign Up", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Engli
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body.container-fluid
    .row
      = render 'layouts/navigation'
      .col-md-6.col-md-offset-3

        - flash.each do |key, value|
          - if value.is_a? (Array)
            div class="alert #{flash_class(key)}"
              - value.each do |message|
                = message
                '.
          - else
            div class="alert #{flash_class(key)}"
              = value

        = yield